Add gcr registry

diff --git a/.github/workflows/fork-state.yml b/.github/workflows/fork-state.yml
--- a/.github/workflows/fork-state.yml
+++ b/.github/workflows/fork-state.yml
@@ -9,9 +9,69 @@ on:
   workflow_dispatch:
 
 env:
+  REGISTRY: "ghcr.io"
+  IMAGE_NAME: "futureversecom/fork-state"
   CARGO_TERM_COLOR: always
 
 jobs:
+    runs-on: [seed-builder]
+    permissions:
+      contents: read
+      packages: write
+    name: Fork the current state and run runtime upgrade
+    steps:
+      - uses: actions/checkout@v3
+        with:
+          fetch-depth: 0
+      - name: ghcr.io login
+        uses: docker/login-action@49ed152c8eca782a232dede0303416e8f356c37b
+        with:
+          registry: ${{ env.REGISTRY }}
+          username: ${{ github.actor }}
+          password: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Create output folder
+        run: mkdir -p output
+
+      #- name: Check out the correct version
+      #  run: |
+      #    python3 -m venv ./scripts/penv
+      #    source ./scripts/penv/bin/activate
+      #    pip install -r ./scripts/requirements.txt
+      #    python3 ./scripts/get_node_version.py  --config ./scripts/networks/porcini.yaml
+
+
+      - name: Build 🛠 & Publish 🐳
+        # build and tag an image with commit hash and 'latest', additionally:
+        # if the commit is tagged, tag the image also e.g. 1.0.0
+        # if the branch name is release/x.x.x tag the image
+        run: |
+          COMMIT_HASH=$(git rev-parse --short HEAD)
+          echo "commit hash: $COMMIT_HASH"
+          COMMIT_TAG=$((git describe --exact-match --tags HEAD) || true)
+          echo "commit tag(?): $COMMIT_TAG"
+          RELEASE_TAG=$(echo -n $GITHUB_REF | grep -oP '(?<=release/).*' || true)
+
+          echo "github ref: $GITHUB_REF"
+          echo "release tag(?): $RELEASE_TAG"
+
+          docker build -t "$REGISTRY/$IMAGE_NAME:$COMMIT_HASH" -t "$REGISTRY/$IMAGE_NAME":latest -f ./dockerimages/fork-state.Dockerfile .
+
+          docker push "$REGISTRY/$IMAGE_NAME:$COMMIT_HASH"
+          docker push "$REGISTRY/$IMAGE_NAME:latest"
+
+          # commit was tagged
+          if [ -n "$COMMIT_TAG" ]; then
+            docker tag "$REGISTRY/$IMAGE_NAME:$COMMIT_HASH" "$REGISTRY/$IMAGE_NAME:$COMMIT_TAG"
+            docker push "$REGISTRY/$IMAGE_NAME:$COMMIT_TAG"
+          fi
+          # branch is a release branch
+          if [ -n "$RELEASE_TAG" ]; then
+            docker tag "$REGISTRY/$IMAGE_NAME:$COMMIT_HASH" "$REGISTRY/$IMAGE_NAME:$RELEASE_TAG"
+            docker push "$REGISTRY/$IMAGE_NAME:$RELEASE_TAG"
+          fi
+          # clean up images
+          docker image prune --filter label=stage=build -f
   build:
     # if: startsWith(github.event.comment.body, '/get_state')
     runs-on: ubuntu-latest
