upd release workflow

diff --git a/.github/workflows/image.yml b/.github/workflows/image.yml
--- a/.github/workflows/image.yml
+++ b/.github/workflows/image.yml
@@ -20,12 +20,10 @@ on:
       - completed
     branches:
       - "release/*"
-      - "release-test" # TODO remove this
   push:
     branches:
       - "main"
       - "release/*"
-      - "release-test" # TODO remove this
     paths:
       - "**.rs"
       - "**.ts"
@@ -42,53 +40,53 @@ env:
   FORK_STATE_IMAGE_NAME: "futureversecom/fork-release-state"
 
 jobs:
-  # build-image:
-  #   if: github.event.workflow_run.conclusion == 'success' || contains(github.ref_name, 'main') || contains(github.ref_name, 'release')
-  #   # only run if release branch CI build passes or its a push to main
-  #   runs-on: [seed-builder]
-  #   permissions:
-  #     contents: read
-  #     packages: write
-  #   steps:
-  #     - uses: actions/checkout@v3
-  #     - name: ghcr.io login
-  #       uses: docker/login-action@49ed152c8eca782a232dede0303416e8f356c37b
-  #       with:
-  #         registry: ${{ env.REGISTRY }}
-  #         username: ${{ github.actor }}
-  #         password: ${{ secrets.GITHUB_TOKEN }}
+  build-image:
+    if: github.event.workflow_run.conclusion == 'success' || contains(github.ref_name, 'main') || contains(github.ref_name, 'release')
+    # only run if release branch CI build passes or its a push to main
+    runs-on: [seed-builder]
+    permissions:
+      contents: read
+      packages: write
+    steps:
+      - uses: actions/checkout@v3
+      - name: ghcr.io login
+        uses: docker/login-action@49ed152c8eca782a232dede0303416e8f356c37b
+        with:
+          registry: ${{ env.REGISTRY }}
+          username: ${{ github.actor }}
+          password: ${{ secrets.GITHUB_TOKEN }}
 
-  #     - name: Build 🛠 & Publish 🐳
-  #       # build and tag an image with commit hash and 'latest', additionally:
-  #       # if the commit is tagged, tag the image also e.g. 1.0.0
-  #       # if the branch name is release/x.x.x tag the image
-  #       run: |
-  #         COMMIT_HASH=$(git rev-parse --short HEAD)
-  #         echo "commit hash: $COMMIT_HASH"
-  #         COMMIT_TAG=$((git describe --exact-match --tags HEAD) || true)
-  #         echo "commit tag(?): $COMMIT_TAG"
-  #         RELEASE_TAG=$(echo -n $GITHUB_REF | grep -oP '(?<=release/).*' || true)
+      - name: Build 🛠 & Publish 🐳
+        # build and tag an image with commit hash and 'latest', additionally:
+        # if the commit is tagged, tag the image also e.g. 1.0.0
+        # if the branch name is release/x.x.x tag the image
+        run: |
+          COMMIT_HASH=$(git rev-parse --short HEAD)
+          echo "commit hash: $COMMIT_HASH"
+          COMMIT_TAG=$((git describe --exact-match --tags HEAD) || true)
+          echo "commit tag(?): $COMMIT_TAG"
+          RELEASE_TAG=$(echo -n $GITHUB_REF | grep -oP '(?<=release/).*' || true)
 
-  #         echo "github ref: $GITHUB_REF"
-  #         echo "release tag(?): $RELEASE_TAG"
+          echo "github ref: $GITHUB_REF"
+          echo "release tag(?): $RELEASE_TAG"
 
-  #         docker build -t "$REGISTRY/$IMAGE_NAME:$COMMIT_HASH" -t "$REGISTRY/$IMAGE_NAME":latest -f ./Dockerfile .
+          docker build -t "$REGISTRY/$IMAGE_NAME:$COMMIT_HASH" -t "$REGISTRY/$IMAGE_NAME":latest -f ./Dockerfile .
 
-  #         docker push "$REGISTRY/$IMAGE_NAME:$COMMIT_HASH"
-  #         docker push "$REGISTRY/$IMAGE_NAME:latest"
+          docker push "$REGISTRY/$IMAGE_NAME:$COMMIT_HASH"
+          docker push "$REGISTRY/$IMAGE_NAME:latest"
 
-  #         # commit was tagged
-  #         if [ -n "$COMMIT_TAG" ]; then
-  #           docker tag "$REGISTRY/$IMAGE_NAME:$COMMIT_HASH" "$REGISTRY/$IMAGE_NAME:$COMMIT_TAG"
-  #           docker push "$REGISTRY/$IMAGE_NAME:$COMMIT_TAG"
-  #         fi
-  #         # branch is a release branch
-  #         if [ -n "$RELEASE_TAG" ]; then
-  #           docker tag "$REGISTRY/$IMAGE_NAME:$COMMIT_HASH" "$REGISTRY/$IMAGE_NAME:$RELEASE_TAG"
-  #           docker push "$REGISTRY/$IMAGE_NAME:$RELEASE_TAG"
-  #         fi
-  #         # clean up images
-  #         docker image prune --filter label=stage=build -f
+          # commit was tagged
+          if [ -n "$COMMIT_TAG" ]; then
+            docker tag "$REGISTRY/$IMAGE_NAME:$COMMIT_HASH" "$REGISTRY/$IMAGE_NAME:$COMMIT_TAG"
+            docker push "$REGISTRY/$IMAGE_NAME:$COMMIT_TAG"
+          fi
+          # branch is a release branch
+          if [ -n "$RELEASE_TAG" ]; then
+            docker tag "$REGISTRY/$IMAGE_NAME:$COMMIT_HASH" "$REGISTRY/$IMAGE_NAME:$RELEASE_TAG"
+            docker push "$REGISTRY/$IMAGE_NAME:$RELEASE_TAG"
+          fi
+          # clean up images
+          docker image prune --filter label=stage=build -f
 
   build-root-fork-image:
     if: github.event.workflow_run.conclusion == 'success' || contains(github.ref_name, 'release')
